version: '3.3'
services:
  mongosally:
    image: mongo:3.6
    volumes:
      - ./storage:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  hermitapp:
    build:
      context: ./hermit
      cache_from:
      - python:3.6-alpine
    image: cherrypy/cherrypy
    volumes:
      - "./hermit:/app"
    env_file:
      - variables.env
    command: python ${CHERRYPY_APP:-app.py}
